#!/usr/bin/env python3
"""
LatencyTest1/test_stm32_leader.py

FIRST TEST - couple B, LEADER side. Run this on the STM32MP257F-DK.

Leader preset under test: functiongemma on CPU (llama.cpp). This boots the LIVE
stm32mp257fdk_leader (same GGUF, same prompts) that main.py would load on
election. The other device (Raspberry Pi) runs test_raspberry_sensing.py as the
person-detection sensing agent, and the tool actually runs on that Pi.

Run (from the IMPLEMENTATION folder, with the Pi sensing agent already up):
    python LatencyTest1/test_stm32_leader.py

Phase 0 - time_to_boot: cold-load the GGUF 10 times, fully evicting between loads,
and record avg +- std of the absolute startup cost (model already downloaded).
Then, for each tool-count config (1, 6, 12, 18, 24), drive the 10 person queries
through the LIVE FunctionGemma prompts, generated by STREAMING so we time
query->first-token (TTFT), query->tool call, tool->result (real skill on the Pi),
result->reply, decode tk/s, and end-to-end.
Results: LatencyTest1/results/leader_stm32_*.json
"""

import sys
import pathlib

_HERE = pathlib.Path(__file__).resolve().parent
_IMPL = _HERE.parent
for _p in (str(_IMPL), str(_HERE)):
    if _p not in sys.path:
        sys.path.insert(0, _p)

import json
import logging
import os

from llama_cpp import Llama

import bench_core
import LeaderLogic.stm32mp257fdk_leader as leadermod
from LeaderLogic.functiongemma_simple_handler import _build_prompt, _parse_calls

log = logging.getLogger("latencytest")

# Match the deployed FunctionGemma handler's generation stops so a tool call halts
# naturally (the handler appends these itself; we stream one level below it).
_STOP = ["<end_of_turn>", "<end_function_call>", "<start_function_response>"]
_DISPATCH_MAX_TOKENS = 256    # mirrors stm32mp257fdk_leader._dispatch
_ANSWER_MAX_TOKENS = 512      # mirrors stm32mp257fdk_leader._answer


def _lc_tools(tool_defs):
    """Normalise tool defs to the flat OpenAI shape _build_prompt expects."""
    out = []
    for td in tool_defs:
        fn = td.get("function", td)
        out.append({"type": "function", "function": {
            "name": fn["name"],
            "description": fn.get("description", ""),
            "parameters": fn.get("parameters", {})}})
    return out


def main():
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s  [%(name)s]  %(levelname)-7s  %(message)s",
        datefmt="%H:%M:%S",
    )

    cfg = json.loads((_IMPL / "software_config.json").read_text())

    loop, transport, discovery = bench_core.start_network(
        "stm32-leader-bench", bench_core.LEADER_PORT)

    # ── Phase 0: time_to_boot (cold GGUF load x10, full evict between) ─────────
    # Resolve the model exactly as the live leader does, and make sure it is on
    # disk BEFORE timing so the samples measure load, not a one-off download.
    _pb, repo, filename, label, _is_fg = leadermod._select_model(0)
    model_path = leadermod._MODELS_DIR / filename
    if not model_path.exists():
        log.info("downloading %s for boot timing ...", filename)
        leadermod._download_model(repo, filename, model_path)

    def _load_fn():
        # Llama kwargs mirror leadermod.boot() for the FunctionGemma path.
        import time as _t
        t0 = _t.perf_counter()
        llm = Llama(model_path=str(model_path), n_ctx=4096,
                    chat_format="functiongemma",
                    n_threads=os.cpu_count() or 4, verbose=False)
        return _t.perf_counter() - t0, llm

    def _unload_fn(llm):
        try:
            llm.close()
        except Exception:
            pass

    log.info("measuring time_to_boot (%s, 10 cold loads) ...", label)
    boot = bench_core.measure_time_to_boot(_load_fn, _unload_fn, n=10)

    # ── Boot the LIVE FunctionGemma leader for the query phase ────────────────
    log.info("booting FunctionGemma leader for the query phase ...")
    wf = leadermod.boot(cfg=cfg, agent_id="stm32-leader-bench",
                        transport=transport, discovery=discovery,
                        bot=None, profile={"score": 0})
    net = wf.net
    llm = wf._llm

    log.info("waiting for the Raspberry person-detection sensing agent ...")
    if not bench_core.wait_for_peer(transport, timeout=60):
        log.error("no sensing peer found - is test_raspberry_sensing.py running on the Pi? aborting")
        return

    # ── LIVE prompts, streamed so we can time TTFT (mirrors _dispatch/_answer) ─
    def dispatch_stream(query, tool_defs):
        lc = _lc_tools(tool_defs)
        messages = [{"role": "developer", "content": leadermod._DISPATCH_SYSTEM_FG},
                    {"role": "user", "content": query}]
        prompt = _build_prompt(messages, lc)
        tokens_in = len(llm.tokenize(prompt.encode("utf-8"), special=True))
        llm.reset()   # cold prefill per query -> comparable, independent timings
        text, ttft_s, gen_s, _ = bench_core.timed_stream(
            ch["choices"][0]["text"] for ch in llm.create_completion(
                prompt=prompt, stream=True, max_tokens=_DISPATCH_MAX_TOKENS,
                temperature=0.0, seed=42, repeat_penalty=1.1,
                top_p=0.95, top_k=64, stop=_STOP))
        tokens_out = max(llm.n_tokens - tokens_in, 0)   # exact (== completion_tokens)
        tps = bench_core.decode_tps(tokens_out, ttft_s, gen_s)

        calls = _parse_calls(text) if lc else []
        if calls:
            try:
                args = json.loads(calls[0]["arguments"])
            except Exception:
                args = {}
            return {"fn": calls[0]["name"], "args": args, "reply_text": "",
                    "ttft_s": ttft_s, "gen_s": gen_s,
                    "tokens_in": tokens_in, "tokens_out": tokens_out, "decode_tps": tps,
                    "prompt": prompt}   # exact FunctionGemma-rendered dispatch prompt
        return {"fn": None, "args": None, "reply_text": text.strip(),
                "ttft_s": ttft_s, "gen_s": gen_s,
                "tokens_in": tokens_in, "tokens_out": tokens_out, "decode_tps": tps,
                "prompt": prompt}

    def answer_stream(query, fn, args, replies, tool_defs):
        tool_call = {"function": {"name": fn, "arguments": args or {}}}
        messages = [
            {"role": "developer", "content": leadermod._ANSWER_SYSTEM},
            {"role": "user", "content": query},
            {"role": "assistant", "content": "", "tool_calls": [tool_call]},
            {"role": "tool", "name": fn,
             "content": json.dumps(replies, ensure_ascii=False)},
        ]
        # Pass the called tool's def for context, as _answer does via last_tool_defs.
        tdmap = {td.get("function", td)["name"]: td.get("function", td) for td in tool_defs}
        called = tdmap.get(fn)
        tools = _lc_tools([called]) if called else None
        prompt = _build_prompt(messages, tools)
        tokens_in = len(llm.tokenize(prompt.encode("utf-8"), special=True))
        llm.reset()
        text, ttft_s, gen_s, _ = bench_core.timed_stream(
            ch["choices"][0]["text"] for ch in llm.create_completion(
                prompt=prompt, stream=True, max_tokens=_ANSWER_MAX_TOKENS,
                temperature=0.0, seed=42, repeat_penalty=1.1,
                top_p=0.95, top_k=64, stop=_STOP))
        tokens_out = max(llm.n_tokens - tokens_in, 0)
        tps = bench_core.decode_tps(tokens_out, ttft_s, gen_s)
        return {"text": text.strip(), "ttft_s": ttft_s, "gen_s": gen_s,
                "tokens_in": tokens_in, "tokens_out": tokens_out, "decode_tps": tps,
                "prompt": prompt}   # exact FunctionGemma-rendered answer prompt

    bench_core.run_leader_benchmark(
        device="stm32",
        preset_label="functiongemma_cpu",
        transport=transport,
        net=net,
        dispatch_stream=dispatch_stream,
        answer_stream=answer_stream,
        reset_fn=None,          # llm.reset() inside the closures keeps queries independent
        time_to_boot=boot,
    )


if __name__ == "__main__":
    main()
