#!/usr/bin/env python3
"""
LatencyTest1/test_raspberry_leader.py

FIRST TEST - couple A, LEADER side. Run this on the RASPBERRY PI 5 + Hailo.

Leader preset under test: qwen3 on the Hailo NPU (Workflow1, the LIVE inference
strategy from complete_workflow.py). The other device (STM32) runs
test_stm32_sensing.py as the person-detection sensing agent, and the tool
actually runs on that STM32.

Run (from the IMPLEMENTATION folder, with the STM32 sensing agent already up):
    python LatencyTest1/test_raspberry_leader.py

Phase 0 - time_to_boot: acquire the Hailo device + load the .hef 10 times, fully
releasing between loads, and record avg +- std of the absolute startup cost.
Then, for each tool-count config (1, 6, 12, 18, 24), drive the 10 person queries
through the LIVE Workflow1 prompts, generated by STREAMING the Hailo token stream
so we time query->first-token (TTFT), query->tool call, tool->result (real skill
on the STM32), result->reply, decode tk/s, and end-to-end.
Results: LatencyTest1/results/leader_raspberry_*.json
"""

import sys
import pathlib

_HERE = pathlib.Path(__file__).resolve().parent
_IMPL = _HERE.parent
for _p in (str(_IMPL), str(_HERE)):
    if _p not in sys.path:
        sys.path.insert(0, _p)

import json
import logging
import time

import bench_core
from LeaderLogic.complete_workflow import (
    Workflow1, DISPATCH_SYSTEM, ANSWER_SYSTEM, _parse_tool_call_from_text)
from LeaderLogic.leader_network import make_network

log = logging.getLogger("latencytest")

# The Hailo genai LLM applies its own chat template inside generate(), so (unlike
# the STM32/llama.cpp path) we cannot capture the exact rendered prompt string.
# We store the messages + attached tools we passed instead, for the JSON record.
_HAILO_PROMPT_NOTE = ("Hailo genai renders its own chat template internally; the "
                      "exact rendered string is not exposed. 'messages' is what was "
                      "passed to generate(); tool descriptions are in this config's 'tools'.")


def _hailo_pieces(wf, messages, tools=None):
    """Stream the Hailo token generator, yielding each token with the qwen3
    turn-end marker stripped (mirrors Workflow1._hailo_generate, one token at a
    time so bench_core.timed_stream can clock the first one)."""
    with wf.llm.generate(
        prompt=messages,
        tools=tools,
        temperature=wf._hailo_temperature,
        seed=wf._hailo_seed,
        max_generated_tokens=wf._hailo_max_tokens,
    ) as gen:
        for token in gen:
            yield token.replace("<|im_end|>", "")


def main():
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s  [%(name)s]  %(levelname)-7s  %(message)s",
        datefmt="%H:%M:%S",
    )

    cfg = json.loads((_IMPL / "software_config.json").read_text())
    dev_cfg = json.loads((_IMPL / "LeaderLogic" / "raspberry_config.json").read_text())

    hef_path = dev_cfg.get("hailo", {}).get("hef_path")
    if not hef_path:
        log.error("no hailo.hef_path in LeaderLogic/raspberry_config.json - cannot run")
        return
    # Resolve relative hef paths against IMPLEMENTATION so cwd does not matter.
    if not pathlib.Path(hef_path).is_absolute():
        hef_path = str(_IMPL / hef_path)

    loop, transport, discovery = bench_core.start_network(
        "raspberry-leader-bench", bench_core.LEADER_PORT)

    # Single shared network (tool registry + dispatcher), wired into the transport
    # + discovery - identical to what piandhailo_leader.boot() builds for workflow1.
    net = make_network(transport, discovery,
                       reply_timeout=cfg.get("timeouts", {}).get("replies", 3.0))

    wf = Workflow1(llm_hef_path=hef_path, net=net, bot=None)

    # ── Phase 0: time_to_boot (acquire device + load .hef x10, full release) ──
    def _load_fn():
        t0 = time.perf_counter()
        wf.activate()                      # acquires VDevice + loads the HEF
        return time.perf_counter() - t0, None

    def _unload_fn(_):
        wf.deactivate()                    # releases the Hailo LLM + VDevice

    log.info("measuring time_to_boot (qwen3 .hef, 10 cold loads) ...")
    boot = bench_core.measure_time_to_boot(_load_fn, _unload_fn, n=10)

    log.info("activating qwen3 on the Hailo NPU for the query phase ...")
    wf.activate()

    log.info("waiting for the STM32 person-detection sensing agent ...")
    if not bench_core.wait_for_peer(transport, timeout=60):
        log.error("no sensing peer found - is test_stm32_sensing.py running on the STM32? aborting")
        wf.deactivate()
        return

    # ── LIVE prompts, streamed so we can time TTFT (mirrors Workflow1 hooks) ───
    def dispatch_stream(query, tool_defs):
        messages = [{"role": "system", "content": DISPATCH_SYSTEM},
                    {"role": "user", "content": query}]
        wf.llm.clear_context()             # Workflow1 clears context each dispatch
        text, ttft_s, gen_s, n = bench_core.timed_stream(
            _hailo_pieces(wf, messages, tools=tool_defs))
        tps = bench_core.decode_tps(n, ttft_s, gen_s)
        parsed = _parse_tool_call_from_text(text)
        prompt = {"messages": messages,
                  "tools_attached": [t.get("function", t)["name"] for t in tool_defs],
                  "note": _HAILO_PROMPT_NOTE}
        # tokens_in: the Hailo genai streaming API does not expose the prompt
        # token count (unlike llama.cpp on the STM32), so it stays None here.
        if parsed is None:
            return {"fn": None, "args": None, "reply_text": text.strip(),
                    "ttft_s": ttft_s, "gen_s": gen_s,
                    "tokens_in": None, "tokens_out": n, "decode_tps": tps, "prompt": prompt}
        return {"fn": parsed.get("name"), "args": parsed.get("arguments", {}),
                "reply_text": "", "ttft_s": ttft_s, "gen_s": gen_s,
                "tokens_in": None, "tokens_out": n, "decode_tps": tps, "prompt": prompt}

    def answer_stream(query, fn, args, replies, tool_defs):
        command = json.dumps({"name": fn, "arguments": args or {}})
        reply_json = json.dumps(replies, ensure_ascii=False)
        messages = [
            {"role": "system", "content": ANSWER_SYSTEM},
            {"role": "user", "content": (
                f"User request: {query}\n"
                f"Command executed: {command}\n\n"
                f"RESULT DATA (write your reply from this; the 'from' field is the device "
                f"that ran the tool, so name it in your answer)\n"
                f"{reply_json}\n"
            )},
        ]
        wf.llm.clear_context()
        text, ttft_s, gen_s, n = bench_core.timed_stream(_hailo_pieces(wf, messages))
        tps = bench_core.decode_tps(n, ttft_s, gen_s)
        prompt = {"messages": messages, "note": _HAILO_PROMPT_NOTE}
        return {"text": text.strip(), "ttft_s": ttft_s, "gen_s": gen_s,
                "tokens_in": None, "tokens_out": n, "decode_tps": tps, "prompt": prompt}

    try:
        bench_core.run_leader_benchmark(
            device="raspberry",
            preset_label="workflow1_qwen3_hailo",
            transport=transport,
            net=net,
            dispatch_stream=dispatch_stream,
            answer_stream=answer_stream,
            reset_fn=None,          # Hailo clears its own context each generation
            time_to_boot=boot,
        )
    finally:
        try:
            wf.deactivate()                  # release the Hailo device for the next couple
        except Exception:
            pass


if __name__ == "__main__":
    main()
